#ifndef RISOVAT_CONSTANTS_H
#define RISOVAT_CONSTANTS_H
int const MOVE_WINDOWS_X = 500;
int const MOVE_WINDOWS_Y = 40;
int const WINDOW_SIMPLE_ART_HEIGHT = 800;
int const WINDOW_SIMPLE_ART_WIDTH = 800;
int const WINDOW_PALETTE_HEIGHT = 300;
int const WINDOW_PALETTE_WIDTH = 200;
int const WINDOW_INSTRUMENTS_HEIGHT = 400;
int const WINDOW_INSTRUMENTS_WIDTH = 85;
int const WINDOW_INSTRUMENTS_BUTTON_WIDTH = 20;
int const WINDOW_INSTRUMENTS_BUTTON_SPACE_WIDTH = 5;
int const WINDOW_INSTRUMENTS_BUTTON_SPACE_HEIGHT = 5;
int const WINDOW_INSTRUMENTS_BUTTON_HEIGHT = 20;
int const NUMBER_OF_INSTR_BUTTONS_IN_STRING = 3;
int const PALETTE_COLOUR_BAR_HEIGHT = 4;
int const BRUSH_SIZE = 2;
int const NUM_OF_INSTRUMENTS = 7;
int const LINE_STEP_OF_BRUSH = BRUSH_SIZE / 2 + 1;
int const SIZE_OF_IMAGES_BUFFER = 16;
enum {N_DEFAULT_BRUSH, N_CIRCLE_BRUSH, N_LINE, N_BUCKET, N_TRUE_LINE, N_UNDO, N_PIPETKA, N_NOTHING};//numbers of instruments
#endif //RISOVAT_CONSTANTS_H
